# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow2.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionNieuw = QAction(MainWindow)
        self.actionNieuw.setObjectName(u"actionNieuw")
        self.actionNieuw.setShortcutContext(Qt.ShortcutContext.WindowShortcut)
        self.actionOpslaan = QAction(MainWindow)
        self.actionOpslaan.setObjectName(u"actionOpslaan")
        self.actionOpslaan_als = QAction(MainWindow)
        self.actionOpslaan_als.setObjectName(u"actionOpslaan_als")
        self.actionSluiten = QAction(MainWindow)
        self.actionSluiten.setObjectName(u"actionSluiten")
        self.actionKopieren = QAction(MainWindow)
        self.actionKopieren.setObjectName(u"actionKopieren")
        self.actionKnippen = QAction(MainWindow)
        self.actionKnippen.setObjectName(u"actionKnippen")
        self.actionPlakken = QAction(MainWindow)
        self.actionPlakken.setObjectName(u"actionPlakken")
        self.actionZoeken = QAction(MainWindow)
        self.actionZoeken.setObjectName(u"actionZoeken")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionLettergrootte = QAction(MainWindow)
        self.actionLettergrootte.setObjectName(u"actionLettergrootte")
        self.actionDatum = QAction(MainWindow)
        self.actionDatum.setObjectName(u"actionDatum")
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionlichte_modus = QAction(MainWindow)
        self.actionlichte_modus.setObjectName(u"actionlichte_modus")
        self.actiondonkere_modus = QAction(MainWindow)
        self.actiondonkere_modus.setObjectName(u"actiondonkere_modus")
        self.actionletters_groter = QAction(MainWindow)
        self.actionletters_groter.setObjectName(u"actionletters_groter")
        self.actionletters_kleiner = QAction(MainWindow)
        self.actionletters_kleiner.setObjectName(u"actionletters_kleiner")
        self.actionRechts = QAction(MainWindow)
        self.actionRechts.setObjectName(u"actionRechts")
        self.actionLinks = QAction(MainWindow)
        self.actionLinks.setObjectName(u"actionLinks")
        self.actionMidden = QAction(MainWindow)
        self.actionMidden.setObjectName(u"actionMidden")
        self.actionVerdelen = QAction(MainWindow)
        self.actionVerdelen.setObjectName(u"actionVerdelen")
        self.actionTijd = QAction(MainWindow)
        self.actionTijd.setObjectName(u"actionTijd")
        self.actionVandaag = QAction(MainWindow)
        self.actionVandaag.setObjectName(u"actionVandaag")
        self.actionAlls_selecteren = QAction(MainWindow)
        self.actionAlls_selecteren.setObjectName(u"actionAlls_selecteren")
        self.actionAlles_selecteren = QAction(MainWindow)
        self.actionAlles_selecteren.setObjectName(u"actionAlles_selecteren")
        self.actionAlles_selecteren.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionCursief = QAction(MainWindow)
        self.actionCursief.setObjectName(u"actionCursief")
        self.actionVet = QAction(MainWindow)
        self.actionVet.setObjectName(u"actionVet")
        self.actionOnderstrepen = QAction(MainWindow)
        self.actionOnderstrepen.setObjectName(u"actionOnderstrepen")
        self.actionAfdrukken = QAction(MainWindow)
        self.actionAfdrukken.setObjectName(u"actionAfdrukken")
        self.actionOver_Efith = QAction(MainWindow)
        self.actionOver_Efith.setObjectName(u"actionOver_Efith")
        self.actionOver_Edith = QAction(MainWindow)
        self.actionOver_Edith.setObjectName(u"actionOver_Edith")
        self.actionOpen_memo = QAction(MainWindow)
        self.actionOpen_memo.setObjectName(u"actionOpen_memo")
        self.actionOpslaan_als_HTML = QAction(MainWindow)
        self.actionOpslaan_als_HTML.setObjectName(u"actionOpslaan_als_HTML")
        self.actionOpslaan_als_Markdown = QAction(MainWindow)
        self.actionOpslaan_als_Markdown.setObjectName(u"actionOpslaan_als_Markdown")
        self.actionNormaliseren = QAction(MainWindow)
        self.actionNormaliseren.setObjectName(u"actionNormaliseren")
        self.actionMemo_lijst = QAction(MainWindow)
        self.actionMemo_lijst.setObjectName(u"actionMemo_lijst")
        self.actionOpen_HTML = QAction(MainWindow)
        self.actionOpen_HTML.setObjectName(u"actionOpen_HTML")
        self.actionOpen_Markdown = QAction(MainWindow)
        self.actionOpen_Markdown.setObjectName(u"actionOpen_Markdown")
        self.actionmd_afbeelding = QAction(MainWindow)
        self.actionmd_afbeelding.setObjectName(u"actionmd_afbeelding")
        self.actionmd_link = QAction(MainWindow)
        self.actionmd_link.setObjectName(u"actionmd_link")
        self.actionPlatte_Tekst = QAction(MainWindow)
        self.actionPlatte_Tekst.setObjectName(u"actionPlatte_Tekst")
        self.actionNotitie = QAction(MainWindow)
        self.actionNotitie.setObjectName(u"actionNotitie")
        self.actionGeen_hoofdletters = QAction(MainWindow)
        self.actionGeen_hoofdletters.setObjectName(u"actionGeen_hoofdletters")
        self.actionSchrift = QAction(MainWindow)
        self.actionSchrift.setObjectName(u"actionSchrift")
        self.actionblauwe_modus = QAction(MainWindow)
        self.actionblauwe_modus.setObjectName(u"actionblauwe_modus")
        self.actionFont = QAction(MainWindow)
        self.actionFont.setObjectName(u"actionFont")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 10, 781, 531))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        self.menuAlgemeen = QMenu(self.menubar)
        self.menuAlgemeen.setObjectName(u"menuAlgemeen")
        self.menuBewerken = QMenu(self.menubar)
        self.menuBewerken.setObjectName(u"menuBewerken")
        self.menuBeeld = QMenu(self.menubar)
        self.menuBeeld.setObjectName(u"menuBeeld")
        self.menuUitlijnen = QMenu(self.menubar)
        self.menuUitlijnen.setObjectName(u"menuUitlijnen")
        self.menuInvoegen = QMenu(self.menubar)
        self.menuInvoegen.setObjectName(u"menuInvoegen")
        self.menuOpmaak = QMenu(self.menubar)
        self.menuOpmaak.setObjectName(u"menuOpmaak")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuMemo = QMenu(self.menubar)
        self.menuMemo.setObjectName(u"menuMemo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAlgemeen.menuAction())
        self.menubar.addAction(self.menuBewerken.menuAction())
        self.menubar.addAction(self.menuBeeld.menuAction())
        self.menubar.addAction(self.menuUitlijnen.menuAction())
        self.menubar.addAction(self.menuInvoegen.menuAction())
        self.menubar.addAction(self.menuOpmaak.menuAction())
        self.menubar.addAction(self.menuMemo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuAlgemeen.addAction(self.actionNieuw)
        self.menuAlgemeen.addAction(self.actionOpslaan)
        self.menuAlgemeen.addAction(self.actionOpslaan_als)
        self.menuAlgemeen.addAction(self.actionOpslaan_als_HTML)
        self.menuAlgemeen.addAction(self.actionOpslaan_als_Markdown)
        self.menuAlgemeen.addSeparator()
        self.menuAlgemeen.addAction(self.actionOpen)
        self.menuAlgemeen.addAction(self.actionOpen_HTML)
        self.menuAlgemeen.addAction(self.actionOpen_Markdown)
        self.menuAlgemeen.addSeparator()
        self.menuAlgemeen.addAction(self.actionAfdrukken)
        self.menuAlgemeen.addSeparator()
        self.menuAlgemeen.addAction(self.actionSluiten)
        self.menuBewerken.addAction(self.actionKopieren)
        self.menuBewerken.addAction(self.actionKnippen)
        self.menuBewerken.addAction(self.actionPlakken)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionZoeken)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionUndo)
        self.menuBewerken.addAction(self.actionRedo)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionAlles_selecteren)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionNormaliseren)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionPlatte_Tekst)
        self.menuBewerken.addAction(self.actionGeen_hoofdletters)
        self.menuBewerken.addAction(self.actionSchrift)
        self.menuBeeld.addAction(self.actionlichte_modus)
        self.menuBeeld.addAction(self.actiondonkere_modus)
        self.menuBeeld.addAction(self.actionblauwe_modus)
        self.menuBeeld.addSeparator()
        self.menuBeeld.addAction(self.actionFont)
        self.menuUitlijnen.addAction(self.actionRechts)
        self.menuUitlijnen.addAction(self.actionLinks)
        self.menuUitlijnen.addAction(self.actionMidden)
        self.menuUitlijnen.addAction(self.actionVerdelen)
        self.menuInvoegen.addAction(self.actionTijd)
        self.menuInvoegen.addAction(self.actionVandaag)
        self.menuInvoegen.addAction(self.actionmd_afbeelding)
        self.menuInvoegen.addAction(self.actionmd_link)
        self.menuOpmaak.addAction(self.actionCursief)
        self.menuOpmaak.addAction(self.actionVet)
        self.menuOpmaak.addAction(self.actionOnderstrepen)
        self.menuHelp.addAction(self.actionOver_Edith)
        self.menuMemo.addAction(self.actionOpen_memo)
        self.menuMemo.addAction(self.actionMemo_lijst)
        self.menuMemo.addAction(self.actionNotitie)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Edith", None))
        self.actionNieuw.setText(QCoreApplication.translate("MainWindow", u"Nieuw", None))
#if QT_CONFIG(shortcut)
        self.actionNieuw.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan.setText(QCoreApplication.translate("MainWindow", u"Opslaan", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan_als.setText(QCoreApplication.translate("MainWindow", u"Opslaan als tekst", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan_als.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSluiten.setText(QCoreApplication.translate("MainWindow", u"Sluiten", None))
#if QT_CONFIG(shortcut)
        self.actionSluiten.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionKopieren.setText(QCoreApplication.translate("MainWindow", u"Kopieren", None))
#if QT_CONFIG(shortcut)
        self.actionKopieren.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionKnippen.setText(QCoreApplication.translate("MainWindow", u"Knippen", None))
#if QT_CONFIG(shortcut)
        self.actionKnippen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlakken.setText(QCoreApplication.translate("MainWindow", u"Plakken", None))
#if QT_CONFIG(shortcut)
        self.actionPlakken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoeken.setText(QCoreApplication.translate("MainWindow", u"Zoeken", None))
#if QT_CONFIG(shortcut)
        self.actionZoeken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Ongedaan maken", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Opnieuw doen", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionLettergrootte.setText(QCoreApplication.translate("MainWindow", u"Lettergrootte", None))
        self.actionDatum.setText(QCoreApplication.translate("MainWindow", u"Datum", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open Tekst", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionlichte_modus.setText(QCoreApplication.translate("MainWindow", u"lichte modus", None))
        self.actiondonkere_modus.setText(QCoreApplication.translate("MainWindow", u"donkere modus", None))
        self.actionletters_groter.setText(QCoreApplication.translate("MainWindow", u"letters groter", None))
#if QT_CONFIG(shortcut)
        self.actionletters_groter.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+=", None))
#endif // QT_CONFIG(shortcut)
        self.actionletters_kleiner.setText(QCoreApplication.translate("MainWindow", u"letters kleiner", None))
#if QT_CONFIG(shortcut)
        self.actionletters_kleiner.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionRechts.setText(QCoreApplication.translate("MainWindow", u"Rechts", None))
        self.actionLinks.setText(QCoreApplication.translate("MainWindow", u"Links", None))
        self.actionMidden.setText(QCoreApplication.translate("MainWindow", u"Midden", None))
        self.actionVerdelen.setText(QCoreApplication.translate("MainWindow", u"Verdelen", None))
        self.actionTijd.setText(QCoreApplication.translate("MainWindow", u"Tijd", None))
#if QT_CONFIG(shortcut)
        self.actionTijd.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionVandaag.setText(QCoreApplication.translate("MainWindow", u"Vandaag", None))
#if QT_CONFIG(shortcut)
        self.actionVandaag.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionAlls_selecteren.setText(QCoreApplication.translate("MainWindow", u"Alls selecteren", None))
        self.actionAlles_selecteren.setText(QCoreApplication.translate("MainWindow", u"Alles selecteren", None))
#if QT_CONFIG(shortcut)
        self.actionAlles_selecteren.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionCursief.setText(QCoreApplication.translate("MainWindow", u"Cursief", None))
#if QT_CONFIG(shortcut)
        self.actionCursief.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionVet.setText(QCoreApplication.translate("MainWindow", u"Vet", None))
#if QT_CONFIG(shortcut)
        self.actionVet.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionOnderstrepen.setText(QCoreApplication.translate("MainWindow", u"Onderstrepen", None))
#if QT_CONFIG(shortcut)
        self.actionOnderstrepen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.actionAfdrukken.setText(QCoreApplication.translate("MainWindow", u"Afdrukken", None))
#if QT_CONFIG(shortcut)
        self.actionAfdrukken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionOver_Efith.setText(QCoreApplication.translate("MainWindow", u"Over Edith", None))
        self.actionOver_Edith.setText(QCoreApplication.translate("MainWindow", u"Over Edith", None))
        self.actionOpen_memo.setText(QCoreApplication.translate("MainWindow", u"Memo", None))
        self.actionOpslaan_als_HTML.setText(QCoreApplication.translate("MainWindow", u"Opslaan als HTML", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan_als_HTML.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan_als_Markdown.setText(QCoreApplication.translate("MainWindow", u"Opslaan als Markdown", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan_als_Markdown.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionNormaliseren.setText(QCoreApplication.translate("MainWindow", u"Normaliseren", None))
#if QT_CONFIG(shortcut)
        self.actionNormaliseren.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionMemo_lijst.setText(QCoreApplication.translate("MainWindow", u"Memo lijst", None))
        self.actionOpen_HTML.setText(QCoreApplication.translate("MainWindow", u"Open HTML", None))
        self.actionOpen_Markdown.setText(QCoreApplication.translate("MainWindow", u"Open Markdown", None))
        self.actionmd_afbeelding.setText(QCoreApplication.translate("MainWindow", u"md afbeelding", None))
#if QT_CONFIG(shortcut)
        self.actionmd_afbeelding.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionmd_link.setText(QCoreApplication.translate("MainWindow", u"md link", None))
#if QT_CONFIG(shortcut)
        self.actionmd_link.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlatte_Tekst.setText(QCoreApplication.translate("MainWindow", u"Platte Tekst", None))
#if QT_CONFIG(shortcut)
        self.actionPlatte_Tekst.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionNotitie.setText(QCoreApplication.translate("MainWindow", u"Notitie", None))
#if QT_CONFIG(shortcut)
        self.actionNotitie.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionGeen_hoofdletters.setText(QCoreApplication.translate("MainWindow", u"Geen hoofdletters", None))
#if QT_CONFIG(shortcut)
        self.actionGeen_hoofdletters.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+U", None))
#endif // QT_CONFIG(shortcut)
        self.actionSchrift.setText(QCoreApplication.translate("MainWindow", u"Schrift", None))
#if QT_CONFIG(shortcut)
        self.actionSchrift.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionblauwe_modus.setText(QCoreApplication.translate("MainWindow", u"blauwe modus", None))
        self.actionFont.setText(QCoreApplication.translate("MainWindow", u"Font en Lettergrootte", None))
#if QT_CONFIG(shortcut)
        self.actionFont.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+F", None))
#endif // QT_CONFIG(shortcut)
        self.menuAlgemeen.setTitle(QCoreApplication.translate("MainWindow", u"Algemeen", None))
        self.menuBewerken.setTitle(QCoreApplication.translate("MainWindow", u"Bewerken", None))
        self.menuBeeld.setTitle(QCoreApplication.translate("MainWindow", u"Beeld", None))
        self.menuUitlijnen.setTitle(QCoreApplication.translate("MainWindow", u"Uitlijnen", None))
        self.menuInvoegen.setTitle(QCoreApplication.translate("MainWindow", u"Invoegen", None))
        self.menuOpmaak.setTitle(QCoreApplication.translate("MainWindow", u"Opmaak", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuMemo.setTitle(QCoreApplication.translate("MainWindow", u"Apps", None))
    # retranslateUi

