# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionNieuw = QAction(MainWindow)
        self.actionNieuw.setObjectName(u"actionNieuw")
        self.actionNieuw.setShortcutContext(Qt.ShortcutContext.WindowShortcut)
        self.actionOpslaan = QAction(MainWindow)
        self.actionOpslaan.setObjectName(u"actionOpslaan")
        self.actionOpslaan_als = QAction(MainWindow)
        self.actionOpslaan_als.setObjectName(u"actionOpslaan_als")
        self.actionSluiten = QAction(MainWindow)
        self.actionSluiten.setObjectName(u"actionSluiten")
        self.actionKopieren = QAction(MainWindow)
        self.actionKopieren.setObjectName(u"actionKopieren")
        self.actionKnippen = QAction(MainWindow)
        self.actionKnippen.setObjectName(u"actionKnippen")
        self.actionPlakken = QAction(MainWindow)
        self.actionPlakken.setObjectName(u"actionPlakken")
        self.actionZoeken = QAction(MainWindow)
        self.actionZoeken.setObjectName(u"actionZoeken")
        self.actionVervangen = QAction(MainWindow)
        self.actionVervangen.setObjectName(u"actionVervangen")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionLettergrootte = QAction(MainWindow)
        self.actionLettergrootte.setObjectName(u"actionLettergrootte")
        self.actionDatum = QAction(MainWindow)
        self.actionDatum.setObjectName(u"actionDatum")
        self.actionInfo = QAction(MainWindow)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 10, 791, 531))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        self.menuAlgemeen = QMenu(self.menubar)
        self.menuAlgemeen.setObjectName(u"menuAlgemeen")
        self.menuBewerken = QMenu(self.menubar)
        self.menuBewerken.setObjectName(u"menuBewerken")
        self.menuBeeld = QMenu(self.menubar)
        self.menuBeeld.setObjectName(u"menuBeeld")
        self.menuDiversen = QMenu(self.menubar)
        self.menuDiversen.setObjectName(u"menuDiversen")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAlgemeen.menuAction())
        self.menubar.addAction(self.menuBewerken.menuAction())
        self.menubar.addAction(self.menuBeeld.menuAction())
        self.menubar.addAction(self.menuDiversen.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuAlgemeen.addAction(self.actionNieuw)
        self.menuAlgemeen.addAction(self.actionOpslaan)
        self.menuAlgemeen.addAction(self.actionOpslaan_als)
        self.menuAlgemeen.addSeparator()
        self.menuAlgemeen.addAction(self.actionOpen)
        self.menuAlgemeen.addSeparator()
        self.menuAlgemeen.addAction(self.actionSluiten)
        self.menuBewerken.addAction(self.actionKopieren)
        self.menuBewerken.addAction(self.actionKnippen)
        self.menuBewerken.addAction(self.actionPlakken)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionZoeken)
        self.menuBewerken.addAction(self.actionVervangen)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionUndo)
        self.menuBewerken.addAction(self.actionRedo)
        self.menuBeeld.addAction(self.actionLettergrootte)
        self.menuDiversen.addAction(self.actionDatum)
        self.menuHelp.addAction(self.actionInfo)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Edith", None))
        self.actionNieuw.setText(QCoreApplication.translate("MainWindow", u"Nieuw", None))
#if QT_CONFIG(shortcut)
        self.actionNieuw.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan.setText(QCoreApplication.translate("MainWindow", u"Opslaan", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan_als.setText(QCoreApplication.translate("MainWindow", u"Opslaan als", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan_als.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSluiten.setText(QCoreApplication.translate("MainWindow", u"Sluiten", None))
#if QT_CONFIG(shortcut)
        self.actionSluiten.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionKopieren.setText(QCoreApplication.translate("MainWindow", u"Kopieren", None))
#if QT_CONFIG(shortcut)
        self.actionKopieren.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionKnippen.setText(QCoreApplication.translate("MainWindow", u"Knippen", None))
#if QT_CONFIG(shortcut)
        self.actionKnippen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlakken.setText(QCoreApplication.translate("MainWindow", u"Plakken", None))
#if QT_CONFIG(shortcut)
        self.actionPlakken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoeken.setText(QCoreApplication.translate("MainWindow", u"Zoeken", None))
#if QT_CONFIG(shortcut)
        self.actionZoeken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionVervangen.setText(QCoreApplication.translate("MainWindow", u"Vervangen", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionLettergrootte.setText(QCoreApplication.translate("MainWindow", u"Lettergrootte", None))
        self.actionDatum.setText(QCoreApplication.translate("MainWindow", u"Datum", None))
        self.actionInfo.setText(QCoreApplication.translate("MainWindow", u"Info", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.menuAlgemeen.setTitle(QCoreApplication.translate("MainWindow", u"Algemeen", None))
        self.menuBewerken.setTitle(QCoreApplication.translate("MainWindow", u"Bewerken", None))
        self.menuBeeld.setTitle(QCoreApplication.translate("MainWindow", u"Beeld", None))
        self.menuDiversen.setTitle(QCoreApplication.translate("MainWindow", u"Invoegen", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

