# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'plaintext3.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QSizePolicy, QStatusBar, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 800)
        self.actionNieuw = QAction(MainWindow)
        self.actionNieuw.setObjectName(u"actionNieuw")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionOpslaan = QAction(MainWindow)
        self.actionOpslaan.setObjectName(u"actionOpslaan")
        self.actionOpslaan_als = QAction(MainWindow)
        self.actionOpslaan_als.setObjectName(u"actionOpslaan_als")
        self.actionSluiten = QAction(MainWindow)
        self.actionSluiten.setObjectName(u"actionSluiten")
        self.actionKopieren = QAction(MainWindow)
        self.actionKopieren.setObjectName(u"actionKopieren")
        self.actionPlakken = QAction(MainWindow)
        self.actionPlakken.setObjectName(u"actionPlakken")
        self.actionKnippen = QAction(MainWindow)
        self.actionKnippen.setObjectName(u"actionKnippen")
        self.actionZoeken = QAction(MainWindow)
        self.actionZoeken.setObjectName(u"actionZoeken")
        self.actionAlles_selecteren = QAction(MainWindow)
        self.actionAlles_selecteren.setObjectName(u"actionAlles_selecteren")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionDatum = QAction(MainWindow)
        self.actionDatum.setObjectName(u"actionDatum")
        self.actionTijd = QAction(MainWindow)
        self.actionTijd.setObjectName(u"actionTijd")
        self.actionmd_link = QAction(MainWindow)
        self.actionmd_link.setObjectName(u"actionmd_link")
        self.actionmd_afbeelding = QAction(MainWindow)
        self.actionmd_afbeelding.setObjectName(u"actionmd_afbeelding")
        self.actionOver_Edith = QAction(MainWindow)
        self.actionOver_Edith.setObjectName(u"actionOver_Edith")
        self.actionNormaliseren = QAction(MainWindow)
        self.actionNormaliseren.setObjectName(u"actionNormaliseren")
        self.actionGeen_hoofdletters = QAction(MainWindow)
        self.actionGeen_hoofdletters.setObjectName(u"actionGeen_hoofdletters")
        self.actionSchrift = QAction(MainWindow)
        self.actionSchrift.setObjectName(u"actionSchrift")
        self.actionDonkere_modus = QAction(MainWindow)
        self.actionDonkere_modus.setObjectName(u"actionDonkere_modus")
        self.actionLichte_modus = QAction(MainWindow)
        self.actionLichte_modus.setObjectName(u"actionLichte_modus")
        self.actionblauwe_modus = QAction(MainWindow)
        self.actionblauwe_modus.setObjectName(u"actionblauwe_modus")
        self.actionFont = QAction(MainWindow)
        self.actionFont.setObjectName(u"actionFont")
        self.actionLettergrootte = QAction(MainWindow)
        self.actionLettergrootte.setObjectName(u"actionLettergrootte")
        self.actionif_name_main = QAction(MainWindow)
        self.actionif_name_main.setObjectName(u"actionif_name_main")
        self.actionSneltoetsen = QAction(MainWindow)
        self.actionSneltoetsen.setObjectName(u"actionSneltoetsen")
        self.actionSneltoetsen_Alt = QAction(MainWindow)
        self.actionSneltoetsen_Alt.setObjectName(u"actionSneltoetsen_Alt")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(9, 9, 1181, 750))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.plainTextEdit = QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        font = QFont()
        font.setFamilies([u"Monospace"])
        font.setPointSize(14)
        font.setBold(True)
        self.plainTextEdit.setFont(font)

        self.verticalLayout.addWidget(self.plainTextEdit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1200, 23))
        self.menuAlgemeen = QMenu(self.menubar)
        self.menuAlgemeen.setObjectName(u"menuAlgemeen")
        self.menuBewerken = QMenu(self.menubar)
        self.menuBewerken.setObjectName(u"menuBewerken")
        self.menuInvoegen = QMenu(self.menubar)
        self.menuInvoegen.setObjectName(u"menuInvoegen")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuBeeld = QMenu(self.menubar)
        self.menuBeeld.setObjectName(u"menuBeeld")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAlgemeen.menuAction())
        self.menubar.addAction(self.menuBewerken.menuAction())
        self.menubar.addAction(self.menuBeeld.menuAction())
        self.menubar.addAction(self.menuInvoegen.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuAlgemeen.addAction(self.actionNieuw)
        self.menuAlgemeen.addAction(self.actionOpen)
        self.menuAlgemeen.addAction(self.actionOpslaan)
        self.menuAlgemeen.addAction(self.actionOpslaan_als)
        self.menuAlgemeen.addSeparator()
        self.menuAlgemeen.addAction(self.actionSluiten)
        self.menuBewerken.addAction(self.actionKopieren)
        self.menuBewerken.addAction(self.actionPlakken)
        self.menuBewerken.addAction(self.actionKnippen)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionZoeken)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionAlles_selecteren)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionUndo)
        self.menuBewerken.addAction(self.actionRedo)
        self.menuBewerken.addSeparator()
        self.menuBewerken.addAction(self.actionNormaliseren)
        self.menuBewerken.addAction(self.actionGeen_hoofdletters)
        self.menuBewerken.addAction(self.actionSchrift)
        self.menuInvoegen.addAction(self.actionDatum)
        self.menuInvoegen.addAction(self.actionTijd)
        self.menuInvoegen.addSeparator()
        self.menuInvoegen.addAction(self.actionmd_link)
        self.menuInvoegen.addAction(self.actionmd_afbeelding)
        self.menuInvoegen.addAction(self.actionif_name_main)
        self.menuHelp.addAction(self.actionOver_Edith)
        self.menuHelp.addAction(self.actionSneltoetsen)
        self.menuHelp.addAction(self.actionSneltoetsen_Alt)
        self.menuBeeld.addAction(self.actionDonkere_modus)
        self.menuBeeld.addAction(self.actionLichte_modus)
        self.menuBeeld.addAction(self.actionblauwe_modus)
        self.menuBeeld.addSeparator()
        self.menuBeeld.addAction(self.actionFont)
        self.menuBeeld.addAction(self.actionLettergrootte)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNieuw.setText(QCoreApplication.translate("MainWindow", u"Nieuw", None))
#if QT_CONFIG(shortcut)
        self.actionNieuw.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan.setText(QCoreApplication.translate("MainWindow", u"Opslaan", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpslaan_als.setText(QCoreApplication.translate("MainWindow", u"Opslaan als", None))
#if QT_CONFIG(shortcut)
        self.actionOpslaan_als.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSluiten.setText(QCoreApplication.translate("MainWindow", u"Sluiten", None))
#if QT_CONFIG(shortcut)
        self.actionSluiten.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionKopieren.setText(QCoreApplication.translate("MainWindow", u"Kopieren", None))
#if QT_CONFIG(shortcut)
        self.actionKopieren.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPlakken.setText(QCoreApplication.translate("MainWindow", u"Plakken", None))
#if QT_CONFIG(shortcut)
        self.actionPlakken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionKnippen.setText(QCoreApplication.translate("MainWindow", u"Knippen", None))
#if QT_CONFIG(shortcut)
        self.actionKnippen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoeken.setText(QCoreApplication.translate("MainWindow", u"Zoeken", None))
#if QT_CONFIG(shortcut)
        self.actionZoeken.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionAlles_selecteren.setText(QCoreApplication.translate("MainWindow", u"Alles selecteren", None))
#if QT_CONFIG(shortcut)
        self.actionAlles_selecteren.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionDatum.setText(QCoreApplication.translate("MainWindow", u"Datum", None))
#if QT_CONFIG(shortcut)
        self.actionDatum.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionTijd.setText(QCoreApplication.translate("MainWindow", u"Tijd", None))
#if QT_CONFIG(shortcut)
        self.actionTijd.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionmd_link.setText(QCoreApplication.translate("MainWindow", u"md link", None))
#if QT_CONFIG(shortcut)
        self.actionmd_link.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionmd_afbeelding.setText(QCoreApplication.translate("MainWindow", u"md afbeelding", None))
#if QT_CONFIG(shortcut)
        self.actionmd_afbeelding.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionOver_Edith.setText(QCoreApplication.translate("MainWindow", u"Over Edith", None))
#if QT_CONFIG(shortcut)
        self.actionOver_Edith.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionNormaliseren.setText(QCoreApplication.translate("MainWindow", u"Normaliseren", None))
#if QT_CONFIG(shortcut)
        self.actionNormaliseren.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionGeen_hoofdletters.setText(QCoreApplication.translate("MainWindow", u"Geen hoofdletters", None))
#if QT_CONFIG(shortcut)
        self.actionGeen_hoofdletters.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+U", None))
#endif // QT_CONFIG(shortcut)
        self.actionSchrift.setText(QCoreApplication.translate("MainWindow", u"Schrift", None))
#if QT_CONFIG(shortcut)
        self.actionSchrift.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionDonkere_modus.setText(QCoreApplication.translate("MainWindow", u"Donkere modus", None))
        self.actionLichte_modus.setText(QCoreApplication.translate("MainWindow", u"Lichte modus", None))
        self.actionblauwe_modus.setText(QCoreApplication.translate("MainWindow", u"blauwe modus", None))
        self.actionFont.setText(QCoreApplication.translate("MainWindow", u"Font", None))
#if QT_CONFIG(shortcut)
        self.actionFont.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionLettergrootte.setText(QCoreApplication.translate("MainWindow", u"Lettergrootte", None))
#if QT_CONFIG(shortcut)
        self.actionLettergrootte.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionif_name_main.setText(QCoreApplication.translate("MainWindow", u"if name == main", None))
        self.actionSneltoetsen.setText(QCoreApplication.translate("MainWindow", u"Sneltoetsen", None))
        self.actionSneltoetsen_Alt.setText(QCoreApplication.translate("MainWindow", u"Sneltoetsen (Alt)", None))
        self.menuAlgemeen.setTitle(QCoreApplication.translate("MainWindow", u"Algemeen", None))
        self.menuBewerken.setTitle(QCoreApplication.translate("MainWindow", u"Bewerken", None))
        self.menuInvoegen.setTitle(QCoreApplication.translate("MainWindow", u"Invoegen", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuBeeld.setTitle(QCoreApplication.translate("MainWindow", u"Beeld", None))
    # retranslateUi

